;;; agent-shell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agent-shell.el

(autoload 'agent-shell "agent-shell" "\
Start or reuse an existing agent shell.

If in a project without a shell, offer to create one.

If already in a shell, invoke `agent-shell-toggle'.

With prefix argument NEW-SHELL, force start a new shell.

(fn &optional NEW-SHELL)" t)
(autoload 'agent-shell-toggle "agent-shell" "\
Toggle agent shell display." t)
(autoload 'agent-shell-new-shell "agent-shell" "\
Start a new agent shell.

Always prompts for agent selection, even if existing shells are available." t)
(autoload 'agent-shell-prompt-compose "agent-shell" "\
Compose an `agent-shell' prompt in a dedicated buffer." t)
(register-definition-prefixes "agent-shell" '("agent-shell-"))


;;; Generated autoloads from agent-shell-anthropic.el

(register-definition-prefixes "agent-shell-anthropic" '("agent-shell-anthropic-"))


;;; Generated autoloads from agent-shell-auggie.el

(register-definition-prefixes "agent-shell-auggie" '("agent-shell-auggie-"))


;;; Generated autoloads from agent-shell-cursor.el

(register-definition-prefixes "agent-shell-cursor" '("agent-shell-cursor-"))


;;; Generated autoloads from agent-shell-diff.el

(register-definition-prefixes "agent-shell-diff" '("agent-shell-"))


;;; Generated autoloads from agent-shell-droid.el

(register-definition-prefixes "agent-shell-droid" '("agent-shell-droid-"))


;;; Generated autoloads from agent-shell-github.el

(register-definition-prefixes "agent-shell-github" '("agent-shell-github-"))


;;; Generated autoloads from agent-shell-google.el

(register-definition-prefixes "agent-shell-google" '("agent-shell-google-"))


;;; Generated autoloads from agent-shell-goose.el

(register-definition-prefixes "agent-shell-goose" '("agent-shell-goose-"))


;;; Generated autoloads from agent-shell-mistral.el

(register-definition-prefixes "agent-shell-mistral" '("agent-shell-mistral-"))


;;; Generated autoloads from agent-shell-openai.el

(register-definition-prefixes "agent-shell-openai" '("agent-shell-openai-"))


;;; Generated autoloads from agent-shell-opencode.el

(register-definition-prefixes "agent-shell-opencode" '("agent-shell-opencode-"))


;;; Generated autoloads from agent-shell-qwen.el

(register-definition-prefixes "agent-shell-qwen" '("agent-shell-qwen-"))


;;; Generated autoloads from agent-shell-ui.el

(autoload 'agent-shell-ui-mode "agent-shell-ui" "\
Minor mode for SUI block navigation.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Ui mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-ui-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "agent-shell-ui" '("agent-shell-ui-"))


;;; Generated autoloads from agent-shell-viewport.el

(register-definition-prefixes "agent-shell-viewport" '("agent-shell-viewport-"))

;;; End of scraped data

(provide 'agent-shell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agent-shell-autoloads.el ends here
