version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: |
            sudo apt update
            curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
            sudo apt-get install --assume-yes nodejs shellcheck
      - run:
          name: Run Tests
          command: make -k
