version: 2.1
workflows:
  test:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:v0.4.6
    steps:
      - run: apk update
      - run: apk add git openssh-client
      - checkout
      - run:
          name: Check Scripts
          command: |
            find '.' -type f -name '*.bash' -exec shellcheck --shell=bash '{}' \+
