#!/usr/bin/env bash

eval "$(/opt/homebrew/bin/brew shellenv)"

# The deprecation warning was hard coded into the macOS bash binary so
# this is the only way to disable it.
# https://support.apple.com/en-us/HT208050
export BASH_SILENCE_DEPRECATION_WARNING=1

source ~/.bashrc

if [[ -r ~/.config/timvisher/ide/bash/bash_profile ]]
then
  source ~/.config/timvisher/ide/bash/bash_profile
fi
